### ISSUE TITLE
Package Description Wording Confusion

### ISSUE THREAD

**Issue by wjk** [wget/chocolatey_openvpn#1]
Hi @wget! I saw your package on Chocolatey.org, and I found a few errors in the nuspec. Specifically, the list of install args in the package description is very confusing to read. It seems that the flags on the left don’t match the explanations on the right. Example:

> `/SELECT_SHORTCUTS=1` : Install the OpenSSL Utilities (used for generating public/private key pairs)
> `/SELECT_LZODLLS=1` : Add OpenVPN shortcuts to the current user's Start Menu

In this case, the description for the `SELECT_LZODLLS` parameter is really meant to be the description for the `SELECT_SHORTCUTS` parameter. Nor is this the only example: Every flag in the description (except for `SELECT_OPENVPN` as far as I can tell) has the wrong description. I would prepare a PR that fixes this, except that I am not familiar with this piece of software, so I am not certain that I would match the flags with descriptions 100% correctly. Thanks!

**Comment by wget** [comment]
@wjk Hi there. You're right. Actually I took the titles and the descriptions from the OpenVPN NSIS sources, and merged them together. I use the Vim text editor and it seems like the command I wrote to merge two text blocks is buggy. Gonna fix this. Thanks for the report.

**Comment by wget** [comment]
Ok my Vim command is working fine :-) This is just the [descriptions](https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L102) in the source code that are not in the same order as the [options](https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L431).

**Comment by wget** [comment]
[Fixed](https://github.com/wget/chocolatey_openvpn/commit/b74294895eb7d9a6fafa3dd805bd33ee312aca24)
