### ISSUE TITLE
Chocolatey version issue

### ISSUE THREAD

**Issue by virgosystems** [wget/chocolatey_openvpn#10]
Hi!
Please find my issue below, pretty much it says all:
`Chocolatey v0.10.15

DEPRECATION NOTICE - choco update is deprecated and will be removed or
 replaced in version 1.0.0 with something that performs the functions
 of updating package indexes. Please use `choco upgrade` instead.
Upgrading the following packages:
openvpn
By upgrading you accept licenses for the packages.

You have openvpn v2.4.6.20190116 installed. Version 2.4.7 is available based on your source(s).
openvpn not upgraded. An error occurred during installation:
 Already referencing a newer version of 'chocolatey'.
openvpn package files upgrade completed. Performing other installation steps.
The upgrade of openvpn was NOT successful.
openvpn not upgraded. An error occurred during installation:
 Already referencing a newer version of 'chocolatey'.
 Unsuccessful operation for openvpn.`

**Comment by wget** [comment]
@virgosystems the error message says it all. Please use choco upgrade instead :)
