### ISSUE TITLE
Is the GPG check still worthwhile?

### ISSUE THREAD

**Issue by EamonNerbonne** [wget/chocolatey_openvpn#11]
Clearly, the gpg check causes issues to pop up occasionally.  Also, I'm not a fan of polluting explorer.exe context menus with additional stuff almost no OpenVPN users are likely to want or expect.

So, what exactly is the threat-model that gpg is intended to protect against here?  I mean, you're already downloading from a trusted source via https, after all.  The number of attackers that can upload to the openvpn binaries but not gain access to the signing certificate (i.e. they didn't hack a dev, and the signing certificate isn't on whatever deploy machine or webserver the attacker did gain access to) seems rather small.

Additionally, by depending on gpgwin, you're *adding* attack surface, because now anybody that hacks the gpgwin infrastructure *or* openvpn (and technically choco and this package, and the gpg package) can gain access to downloaders' machines.  And as it happens, gpg4win-vanilla is currently unmaintained.

So... is this check really doing anything at all?  Isn't best to just dump it?

**Comment by mattock** [comment]
Disclaimer: I'm the one who GPG-signs the official OpenVPN installers.

_If_ a malicious person is somehow able to modify files on the OpenVPN download server then the GPG check will prevent a tampered installer from being run. That said, the tampered installer would also _not_ have OpenVPN Inc's Authenticode (code-signing) signature and normally Windows would show either some other publisher or "Unknown publisher". I'm not sure what Chocolatey does in this case. If the Chocolatey package can be made to stop if the installer does not have correct Authenticode signature then I think the additional GPG check is redundant.

**Comment by wget** [comment]
@mattock I asked the Choco team about this topic. They should get back to me.

But from my understanding choco is not checking the publisher.
So the solution I have to have the gpg check more robust: add to the chocolatey-core.extension Posh wrapper around the BountyCastle C# implementation.

In the meantime, I'll keep the existing gpg check even if I need to publish a dot release to the package afterwards :)

**Comment by wget** [comment]
Revived at https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/openvpn
which is not checking for GPG signatures any more.

Closing.
