### ISSUE TITLE
Releasing a package for OpenVPN 2.4.8?

### ISSUE THREAD

**Issue by mattock** [wget/chocolatey_openvpn#12]
When working on Puppet code that needs to run on Windows 10 ARM64 I noticed that the Chocolatey OpenVPN package is still at 2.4.7. That means that the bundled tap-windows6 driver is also old, has some already fixed security issues and does not have ARM64 support.

The current 2.4.8 installers have up-to-date drivers which work across all Windows versions:
* [Windows 7/8/8.1/Server 2012r2 installer](https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.8-I602-Win7.exe)
* [Windows 10/Server 2016/Server 2019 installer](https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.8-I602-Win10.exe)

Would it be possible to update the Chocolatey package to 2.4.8?

**Comment by C-Duv** [comment]
According to [this Disqus comment](http://disq.us/p/25gygvx) on [`openvpn` Chocolatey package page](https://chocolatey.org/packages/openvpn) it is planned:
> Hello everyone. We are aware of the OpenVPN 2.4.8 release. Please wait a bit while we implement some changes that has been requested to this package.
> 
> 1) We will now detect whether the OpenVPN-GUI is running and restart it to avoid C++ lib runtime missmatch after an update has been applied
> 2) We will remove the gpg4win-vanilla dependency and upstream GPG verification directly to Chocolatey as a core team extension.
> 3) As two install packages are now being provided by OpenVPN Inc (one for the Windows 7 family and another for Windows 10), we decided to implement a OS version detection directly as a Chocolatey core team extension.
> 
> For more details, please follow the GitHub repository of this package. Keep you posted :)

**Comment by CMCDragonkai** [comment]
I want to install the modern gnupg. Will this package work with that or result in a conflict?

**Comment by CMCDragonkai** [comment]
Ok, instead of that, when this package gets updated and removes gpg4wn, then when I update this package, can it please also remove gpg4win at the same time, so I can then install the proper gnupg package as well?

**Comment by grnassar** [comment]
Where is development occurring for this?  The Github repo has a last-touch date of March of last year, which is well prior to the dev's message in the Chocolatey discussion.  So I imagine development is occurring elsewhere?

**Comment by wget** [comment]
Nope, it was a bit stagnant :) Closing this as I'm updating to 2.5.0 right away. I don't think I need to maintain or push a 2.4.x package for now since the .msi installers are fixing the aforementioned tap driver signatures we had with the different version of Windows we support.

Please reopen if you **really** need a 2.4.x branch :)

**Comment by b-reich** [comment]
@wget the choco release site says it is still on 2.4.7, we are now on 2.5.4. Can I help you?
