### ISSUE TITLE
OpenVPN is outdated

### ISSUE THREAD

**Issue by f1x1t1x1f** [wget/chocolatey_openvpn#14]
can you please update to the neu Version 2.5.x

**Comment by dgowdy** [comment]
Any update on this?

**Comment by pauby** [comment]
@wget The OpenVPN package is out of date. Last update we had on the Disqus comments was a year ago talking about removing the `gpg4win-vanilla` dependency (which is deprecated) and an update to 2.4.8. Can you provide an update on what is happening with it?

**Comment by opoplawski** [comment]
ping?  Any help needed with testing?

**Comment by pauby** [comment]
I've reached out to wget via Gitter.

**Comment by wget** [comment]
Hi there. Thanks pauby for the nudge. Sue, I've seen this issue.

What I need to do for this:
* extend the official chocolatey extensions with the PGP functions I wrote
* when this ^ is merged, update the 2.4 branch with the latest version
* then remove the .exe specific calls to an .msi installer for the 2.5 branch

So this will require some time, and I'll need Chocolatey's help to review the patches I'll upstream.

When the 2.5 branch (which introduces an .msi installer is live), we will be able to move the package to the [core team packages repo](https://github.com/chocolatey-community/chocolatey-coreteampackages).

The GPG and lack of msi installer was preventing me to make t a core package :/

**Comment by pauby** [comment]
@wget Are we saying that this can't move forward until there are changes in Chocolatey? That's not guaranteed to happen, and it won't happen quickly. I don't feel we can wait for that to happen.

Can we move to the 2.5 installer now? It's available.

**Comment by pauby** [comment]
@wget Where are we with this?

**Comment by wget** [comment]
I can provide a new ETA: tomorrow end of day, we will get the latest 2.4 version and also the 2.5 version published.

**Comment by f1x1t1x1f** [comment]
@wget When can we expect the new version?

**Comment by swaitz-solactive** [comment]
@wget Any news on the release? We would love to install 2.5.0 via choco.

**Comment by mattock** [comment]
We're at 2.5.2 now. Also, 2.5.3 may be coming out this week.

**Comment by pauby** [comment]
This package has now been picked up by a [new maintainer](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1024) and hopefully we can get a new package out soon.

@wget if you are able to reach out to him and offer any advice that you had with working on the newer versions that would be really appreciated.

**Comment by jedfrechette** [comment]
@wget and  @dgalbraith has any progress been made on updating this package? Thanks.

**Comment by pauby** [comment]
@jedfrechette See [this issue](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1024)

**Comment by wget** [comment]
Revived at https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/openvpn

Closing.
