### ISSUE TITLE
Is the OpenSSL version distributed with OpenVPN up to date?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [wget/chocolatey_openvpn#15]
Within here it appears that there's an OpenSSL version distributed:
C:\Program Files\OpenVPN\bin
OpenSSL> version
OpenSSL 1.1.0j  20 Nov 2018

According to https://www.openssl.org/news/vulnerabilities-1.1.0.html , this seems to be relatively old, and 1.1.0 seems to be out of support.

Is this something that could do to be updated, or have I got hold of the wrong end of the stick and the openssl.exe in "OpenVPN\bin" isn't coming from here?

I'm guessiing that this might get resolved as part of https://github.com/wget/chocolatey-package-openvpn/issues/14 and https://github.com/chocolatey-community/chocolatey-package-requests/issues/1024#issuecomment-940129965 , but am mentioning it just in case.

**Comment by wget** [comment]
Revived at https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/openvpn

Closing.
