### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by ccraigieTM** [wget/chocolatey_openvpn#16]
This package hasn't been update in nearly 3 years.  Is it abandoned?

**Comment by mattock** [comment]
It sure smells like it. Forking it might make sense, but I'm not volunteering.

**Comment by 29039** [comment]
Seems like it... 

https://github.com/chocolatey-community/chocolatey-package-requests/issues/1024

Not sure what's going on.

**Comment by wget** [comment]
Revived at https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/openvpn

Closing.
