### ISSUE TITLE
OpenVPN 2.4.2 release on Thursday at 16:00 CEST

### ISSUE THREAD

**Issue by mattock** [wget/chocolatey_openvpn#4]
The OpenVPN project will release OpenVPN 2.4.2 and 2.3.15 the upcoming Thursday (11th May) at 16:00 CEST. These two releases will contain important security fixes and we hope that you could update the Chocolatey package fairly quickly after the release.

**Comment by wget** [comment]
Sure will do. It's put in my agenda :)

**Comment by mattock** [comment]
@wget great, thanks!

**Comment by wget** [comment]
Currently deploying locally, then pushing upstream to choco repo :)

**Comment by wget** [comment]
Published.
