### ISSUE TITLE
Use standalone gpgv executable instead of depending on gpg4win-vanilla

### ISSUE THREAD

**Issue by fghzxm** [wget/chocolatey_openvpn#8]
GPG signature checking is only performed at install time to verify the OpenVPN installer, therefore it may be a good idea to include a standalone `gpgv` executable in the package and get rid of dependency on `gpg4win-vanilla`.

(Actually the bigger problem is that `gpg4win-vanilla` and the full-fledged `Gpg4win` package do not play well and interfered with each other's software registry on my system.  Ideally we should have `Gpg4win` depend on `gpg4win-vanilla` and provide by itself only the delta, but a standalone `gpgv` in this package should be beneficial nevertheless.)

**Comment by wget** [comment]
Related to #7 .
